version: '3.8'
services:
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://root:root_password@db:5432/webshop
      JWT_SECRET: my_jwt_secret
    command: sh -c "npx prisma migrate deploy && node dist/app.js"
    networks:
      - my-network
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: webshop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - my-network
volumes:
  postgres-data:
networks:
  my-network: