version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: webshop-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend-node
    container_name: backend
    environment:
     - DATABASE_URL="postgresql://root:root_password@localhost:5432/webshop?schema=public"
     - JWT_SECRET=my_jwt_secret
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres-data: