version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://root:root_password@db:5432/webshop
      JWT_SECRET: my_jwt_secret
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: webshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: