INSERT INTO public."Product" (title,description,price,sizes,images,gender) VALUES
	 ('Botine piele naturală 453C color','Modelul trendy fac aceste botine sa fie alegerea preferata de multe din clientele noastre. Tocul usor inalt si designul unic vor face sa fii remarcata. Combinatia de culori  este usor de asortat si perfecta pentru o tinuta casual. Un produs de calitate prelucrat manual. Inaltime toc: 5.5 cm',269.0,'[36, 37, 38, 39, 40]','["assets/botine-piele-naturala-453c-01.avif", "assets/botine-piele-naturala-453c-02.avif", "assets/botine-piele-naturala-453c-03.avif"]','female'),
	 ('Botine piele naturală 558 negru velur','Botine din piele naturala velur concepute special pentru confortul tau. Tocul confortabil si designul atragator te ajuta sa te simti confortabila ori de cate ori vei purta acest model. Interiorul captusit cu piele naturala, perfecte pentru zilele de toamna. Aceasta culoare este usor de asortat si perfecta pentru o tinuta casual/elegant. Tocul este foarte confortabil. Inaltime toc: 4.5 cm',259.0,'[36, 37, 38, 39, 40]','["assets/botine-piele-mark-558-negru-01.avif", "assets/botine-piele-mark-558-negru-02.avif"]','female'),
	 ('Botine din piele 559 maro','Botine din piele naturala cu toc confortabil usor de incaltat si asortat. Tocul mic te ajuta sa te simti confortabila ori de cate ori vei purta acest model. Interiorul captusit cu material termoizolant te protejează de frig in zilele reci de toamna sau iarna. Aceasta culoare  este usor de asortat si perfecta pentru o tinuta casual/elegant. Prevazute cu fermoar lateral. Tocul este foarte confortabil. Inaltime toc: 4.5 cm',249.0,'[36, 37, 38, 39, 40]','["assets/botine-din-piele-559-01.avif", "assets/botine-din-piele-559-02.avif"]','female'),
	 ('Ghete din piele 560 negru','Ghete din piele imblanite special pentru confortul tau. Calduroase - imblanite cu lana naturala. Brantul anatomic iti ofera confortul dorit. Talpa cauciucata si antiderapanta. Cusut pentru iarna pentru a nu permite infiltrarea apei. Piele naturala velur',269.0,'[36, 37, 38, 39, 40]','["assets/ghete-piele-560-01.avif", "assets/ghete-piele-560-02.avif"]','female'),
	 ('Sandale din piele naturală 258 color','Pentru a beneficia de un mers confortabil si natural, aceste sandale din piele naturala sunt recomandarea noastra. Încălţăminte de damă. Partea superioară şi tălpicul din piele naturală. Manoperă de înaltă calitate. Catarama reglabila. Formă anatomică.',179.0,'[35, 36, 37, 38, 39, 40]','["assets/sandale-piele-258-color-01.avif", "assets/sandale-piele-258-color-02.avif", "assets/sandale-piele-258-color-03.avif", "assets/sandale-piele-258-color-04.avif"]','female'),
	 ('Sandale din piele naturală 281 rosu velur','Pentru a beneficia de un mers confortabil si natural, aceste sandale din piele naturala sunt recomandarea noastra. Bareta reglabilă. Partea superioară şi tălpicul din piele naturală. Manoperă de înaltă calitate. Catarama reglabila. Formă anatomică.',166.0,'[35, 36, 37, 38, 39, 40]','["assets/sandale-din-piele-naturala-258-01.avif", "assets/sandale-din-piele-naturala-258-02.avif", "assets/sandale-din-piele-naturala-258-03.avif"]','female'),
	 ('Sandale din piele naturală 279 crem','Pentru a beneficia de un mers confortabil si naturala aceste sandalele din piele naturala sunt alegerea perfecta. Partea superioară şi tălpicul din piele naturală. Talpa asigură un mers uşor şi natural. Manoperă de înaltă calitate. Bareta reglabila. Inaltimea tocului: 6 cm',229.0,'[36, 37, 38, 39, 40]','["assets/sandale-din-piele-naturala-279-maro-01.avif", "assets/sandale-din-piele-naturala-279-maro-02.avif"]','female'),
	 ('Sandale din piele naturală 279 negru','Pentru a beneficia de un mers confortabil si naturala aceste sandalele din piele naturala sunt alegerea perfecta. Partea superioară şi tălpicul din piele naturală. Talpa asigură un mers uşor şi natural. Manoperă de înaltă calitate. Bareta reglabila. Inaltimea tocului: 6 cm',229.0,'[36, 37, 38, 39, 40]','["assets/sandale-din-piele-naturala-279-negru-01.avif", "assets/sandale-din-piele-naturala-279-negru-02.avif"]','female'),
	 ('Sandale din piele naturală 260 negru','Pentru a beneficia de un mers confortabil si naturala aceste sandalele din piele naturala sunt alegerea perfecta. Partea superioară şi tălpicul din piele naturală. Talpa asigură un mers uşor şi natural. Manoperă de înaltă calitate. Bareta reglabila prin scai. Inaltimea tocului: 7 cm',229.0,'[36, 37, 38, 39, 40]','["assets/sandale-piele-naturala-260-negru_01.avif", "assets/sandale-piele-naturala-260-negru_02.avif", "assets/sandale-piele-naturala-260-negru_03.avif"]','female'),
	 ('Pantofi piele naturala 646 rosu','Botine din piele naturala concepute special pentru confortul tau. Tocul confortabil si designul atragator te ajuta sa te simti confortabila ori de cate ori vei purta acest model. Interiorul captusit cu material termoizolant te protejează de frig in zilele reci de toamna sau iarna. Aceasta culoare  este usor de asortat si perfecta pentru o tinuta casual/elegant. Tocul este foarte confortabil.',294.0,'[36, 37, 38, 39, 40]','["assets/pantofi-piele-naturala-646-rosu-110650.jpg", "assets/pantofi-piele-naturala-646-rosu-049982.jpg", "assets/pantofi-piele-naturala-646-rosu-364208.jpg"]','female');
INSERT INTO public."Product" (title,description,price,sizes,images,gender) VALUES
	 ('Sandale din piele naturală 281 albastru','Pentru a beneficia de un mers confortabil si natural, aceste sandale din piele naturala sunt recomandarea noastra. Bareta reglabilă. Partea superioară şi tălpicul din piele naturală. Manoperă de înaltă calitate. Catarama reglabila. Formă anatomică.',166.0,'[35, 36, 37, 38, 39, 40]','["assets/sandale-piele-naturala-033-albastru-113299.jpg", "assets/sandale-piele-naturala-033-albastru-221712.jpg", "assets/sandale-piele-naturala-033-albastru-058205.jpg"]','female'),
	 ('Pantofi casual dama 595 negru velur','Pantofi din piele naturala velur conceputi pentru confortul tau. Talpa moale te ajuta sa te simti confortabil ori de cate ori vei purta acest model. Sunt din piele naturala de foarte buna calitate. Design elegant, simplu și foarte usori. Talpic spuma EVA acoperit cu brant de piele. Inaltime toc: 4.5 cm',259.0,'[36, 37, 38, 39, 40]','["assets/pantofi-casual-dama-595-negru-velur-6136-6946.jpg", "assets/pantofi-casual-dama-595-negru-copie-6136-4727.jpg"]','female'),
	 ('Ghete casual din piele naturală 1037 negru','Talpa extra light si ultra rezistenta. Căptușeala din lâna naturală. Usor de intretinut. Talpic din piele naturala. Se inchid cu siret/fermoar. Rezistenti la apa',299.0,'[40, 41, 42, 43, 44, 45]','["assets/pantofi-casual-din-piele-naturala-1037-01.avif", "assets/pantofi-casual-din-piele-naturala-1037-02.avif", "assets/pantofi-casual-din-piele-naturala-1037-03.avif"]','male'),
	 ('Pantofi casual din piele naturală 1036 negru','Talpa extra light si ultra rezistenta. Căptușeala din lâna naturală. Usor de intretinut. Talpic din piele naturala. Se inchid cu siret/fermoar. Rezistenti la apa',299.0,'[40, 41, 42, 43, 44, 45]','["assets/art-1036-n-01.avif", "assets/art-1036-n-02.avif", "assets/art-1036-n-03.avif", "assets/art-1036-n-04.avif"]','male'),
	 ('Pantofi casual din piele naturală 1020 maro','Usor de intretinut. Talpic din piele naturala. Se inchid cu siret. Rezistenti la apa',259.0,'[40, 41, 42, 43, 44, 45]','["assets/piele-naturala-1020-01.avif", "assets/piele-naturala-1020-02.avif", "assets/piele-naturala-1020-03.avif"]','male'),
	 ('Pantofi piele naturala 647 bej','Modelul trendy fac aceste botine sa fie alegerea preferata de multe din clientele noastre. Tocul usor inalt si designul unic vor face sa fii remarcata. Combinatia de culori  este usor de asortat si perfecta pentru o tinuta casual. Un produs de calitate prelucrat manual. Inaltime toc: 5.5 cm',269.0,'[36, 37, 38, 39, 40]','["assets/pantofi-piele-naturala-647-albastru-copie-043085.jpg", "assets/pantofi-piele-naturala-647-albastru-copie-501543.jpg", "assets/pantofi-piele-naturala-647-albastru-copie-547892.jpg"]','female');
